X_test <- `colnames<-`(X_test, features$V2)
X_train <- `colnames<-`(X_train, features$V2)
subject_test <- data.frame(subject = subject_test$V1)
subject_train <- data.frame(subject = subject_train$V1)
activity_labels <- data.frame(V1 = activity_labels$V1, activity = activity_labels$V2)
features <- data.frame(features = gsub("meanFreq", "freq", features$V2))
mean_sd <- grep('mean()|std()', features$features, value = TRUE)
x_test_set <- subset(X_test, select = mean_sd)
x_train_set <- subset(X_train, select = mean_sd)
x_test_set <- cbind(subject_test, y_test, x_test_set)
x_train_set <- cbind(subject_train, y_train, x_train_set)
data <- rbind(x_test_set, x_train_set)
library(plyr)
data_set <- join(data, activity_labels, by = "V1")
library(dplyr)
mean_subject <- data.frame(subject = data_set$subject, select(data_set, 3:68))
mean_subject <- aggregate(. ~ subject, data = mean_subject, FUN = mean)
mean_activity <- data.frame(activity = data_set$activity, select(data_set, 3:68))
mean_activity <- aggregate(. ~ activity, data = mean_activity, FUN = mean)
final_data <- cbind(mean_subject, mean_activity)
